apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-wording-app
  labels:
    name: simple-wording_app-deployment
spec:
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: simple-wording-app
          image: balajidevops1/myjavaspringbootapp:18
  replicas: 3
